"""vouch_filter.py — PACK 57 §S (57-18) public-repo clanker filter logic.

TEMPLATE ARTIFACT for the PUBLIC `Aethermate-releases` repo — it is intentionally
NOT a live module in this (private) repo: wiring a vouch auto-close Action here
would close Chad's own (and this agent's) PRs. Copy this file + the workflow +
VOUCHED.txt into `Aethermate-releases` (see README.md) to arm it there.

Mirrors Mario Zechner's + Mitchell Hashimoto's `vouch`: drive-by AI-agent
("clanker") PRs from unknown accounts are auto-closed with ONE fixed human-voice
request (no bot boilerplate, one screen); a maintainer's "looks good" adds the
account to VOUCHED.txt; issues from obvious agent traffic get a `needs-human`
label for a human to triage rather than being closed.

Pure stdlib, no network — the workflow feeds it the event JSON on stdin and reads
VOUCHED.txt from the checkout, so the SAME logic is unit-tested in the Aethermate
repo (tests/test_vouch_filter.py) and run unchanged in the Action."""
from __future__ import annotations

import json
import sys
from typing import Any, Iterable

# The fixed, human-voice close message. No "I am a bot", no checklist, one screen.
REQUEST_COMMENT = (
    "Thanks for the interest in Aethermate.\n\n"
    "This repo takes changes from a small set of vouched contributors so review "
    "stays human-paced. I'm closing this for now — nothing personal, and not a "
    "judgement on the change.\n\n"
    "If you'd like to contribute: open an issue describing what you're trying to "
    "fix or add, in your own words, and we'll talk it through. Once we've had that "
    "conversation I'll vouch for your account and your PRs will stay open.\n"
)

# A maintainer comment containing any of these (case-insensitive) vouches the
# PR author — the Action then appends their login to VOUCHED.txt.
VOUCH_PHRASES = ("looks good", "lgtm", "/vouch", "vouched")

# Heuristic markers of drive-by agent traffic on ISSUES (labeled, never closed).
_AGENT_MARKERS = (
    "as an ai language model",
    "as a large language model",
    "i am an ai",
    "generated by",
    "🤖 generated with",
    "this pull request was created automatically",
)


def _norm(login: str) -> str:
    return str(login or "").strip().lstrip("@").lower()


def load_vouched(text: str) -> set[str]:
    """Parse VOUCHED.txt: one login per line, '#' comments and blanks ignored."""
    out: set[str] = set()
    for raw in str(text or "").splitlines():
        line = raw.split("#", 1)[0].strip()
        if line:
            out.add(_norm(line))
    return out


def is_vouched(login: str, vouched: Iterable[str]) -> bool:
    return _norm(login) in {_norm(v) for v in vouched}


def comment_vouches(body: str) -> bool:
    """True if a maintainer comment body contains a vouch phrase."""
    b = str(body or "").lower()
    return any(p in b for p in VOUCH_PHRASES)


def looks_like_agent(*texts: str) -> bool:
    blob = "\n".join(str(t or "") for t in texts).lower()
    return any(m in blob for m in _AGENT_MARKERS)


def classify_pr(author: str, vouched: Iterable[str]) -> dict:
    """Decide the action for a newly-opened PR. `close` PRs get REQUEST_COMMENT
    and the `unvouched` label; vouched authors are left open."""
    if is_vouched(author, vouched):
        return {"action": "keep", "label": None, "comment": None, "reason": "vouched author"}
    return {
        "action": "close",
        "label": "unvouched",
        "comment": REQUEST_COMMENT,
        "reason": "author not in VOUCHED.txt",
    }


def classify_issue(author: str, title: str, body: str, vouched: Iterable[str]) -> dict:
    """Issues are never auto-closed. An unvouched author whose issue shows obvious
    agent markers gets `needs-human` for a maintainer to triage."""
    if is_vouched(author, vouched):
        return {"action": "keep", "label": None, "reason": "vouched author"}
    if looks_like_agent(title, body):
        return {"action": "label", "label": "needs-human", "reason": "agent markers, unvouched"}
    return {"action": "keep", "label": None, "reason": "unvouched but human-looking; leave for triage"}


def _event_from(payload: dict) -> dict:
    """Map a GitHub webhook/event payload to a decision. Supports pull_request and
    issues `opened`, and issue_comment `created` (the vouch path)."""
    vouched = load_vouched(payload.get("_vouched_txt", ""))
    if "pull_request" in payload and "comment" not in payload:
        author = (payload.get("pull_request", {}).get("user", {}) or {}).get("login", "")
        return {"kind": "pull_request", **classify_pr(author, vouched)}
    if "issue" in payload and "comment" in payload:
        # a maintainer comment — does it vouch the issue/PR author?
        body = (payload.get("comment", {}) or {}).get("body", "")
        target = (payload.get("issue", {}).get("user", {}) or {}).get("login", "")
        if comment_vouches(body):
            return {"kind": "vouch", "action": "vouch", "login": _norm(target),
                    "reason": "maintainer vouch phrase"}
        return {"kind": "comment", "action": "noop", "reason": "no vouch phrase"}
    if "issue" in payload:
        issue = payload.get("issue", {})
        author = (issue.get("user", {}) or {}).get("login", "")
        return {"kind": "issue",
                **classify_issue(author, issue.get("title", ""), issue.get("body", ""), vouched)}
    return {"kind": "unknown", "action": "noop", "reason": "unrecognised event"}


def main(argv: list[str] | None = None) -> int:
    """CLI: reads an event payload JSON on stdin (with a `_vouched_txt` key carrying
    VOUCHED.txt contents) and prints the decision as JSON. Exit 0 always — the
    Action inspects the JSON, the filter never fails a run."""
    try:
        payload: Any = json.load(sys.stdin)
        if not isinstance(payload, dict):
            payload = {}
    except Exception:
        payload = {}
    print(json.dumps(_event_from(payload)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
